; SmartDoor - ESP32 firmware (Serial ↔ WebSocket bridge)

[env:pico32]
platform = espressif32
board = pico32
framework = arduino
lib_deps =
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^7.1.0
monitor_speed = 115200
